version: '3.4'

services:
  volttron1:
    container_name: volttron1
    hostname: volttron1
    image: eclipsevolttron/volttron:test-build
    ports:
      # host_port:container_port
      # http port for volttron central
      - 8443:8443
    volumes:
      - ./platform_config.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
      - volttron1-volume:/home/volttron/db
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000

volumes:
  volttron1-volume:
    name: volttron1-data
