ARG image_user=amd64
ARG image_repo=debian
ARG image_tag=9

FROM ${image_user}/${image_repo}:${image_tag}

# copy the local qemu interpreter layer
# NOTE: this file is *not* provided in the repo, it needs to be installed via your package manager and copied here
COPY this_qemu QEMU_TARGET_LOCATION
