name: Create and Merge Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  createrelease:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
        
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "release/v${{ github.event.inputs.versionName }}"
        destination_branch: "main"                      # If blank, default: master
        pr_title: "Merge release/v${{ github.event.inputs.versionName }} into main" # Title of pull request
        pr_label: "automerge"                               # Comma-separated list (no spaces)
        github_token: ${{ env.GITHUB_TOKEN }}

    - name: automerge
      uses: "pascalgn/automerge-action@v0.14.3"
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        LOG: "TRACE"
        
    - name: Create a tag
      run: | 
        echo "Current tags"
        git tag 
        echo "Creating new tag ${{ github.event.inputs.versionName }}"
        git tag "v${{ github.event.inputs.versionName }}"
        git tag
        git push origin "v${{ github.event.inputs.versionName }}"
