name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  createrelease:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com

    - name: Run Changelog CI
      uses: saadmk11/changelog-ci@v1.0.0
      with:
        # Optional, you can provide any name for your changelog file,
        # We currently support Markdown (.md) and reStructuredText (.rst) files
        # defaults to `CHANGELOG.md` if not provided.
        changelog_filename: CHANGELOG.md
        # Optional, This will be used to configure git
        # defaults to `github-actions[bot]` if not provided.
        committer_username: 'GitHub Actions'
        committer_email: 'noreply@github.com'
        release_version: ${{ github.event.inputs.versionName }}
        # Optional
        github_token: ${{ env.GITHUB_TOKEN }}
      
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add CHANGELOG.md
        git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
        
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}

    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       github-token: ${{ env.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.versionName }}
       base: main
       title: v${{ github.event.inputs.versionName }} into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response to running a GithubAction workflow.
    
    - name: Create a tag
      run: | 
        echo "Current tags"
        git tag 
        echo "Creating new tag ${{ github.event.inputs.versionName }}"
