name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  createrelease:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
        
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ env.GITHUB_TOKEN }}
        commit-message: "Merge release ${{ github.event.inputs.versionName }} into main"
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        base: main
        delete-branch: false
        title: "Merge release ${{ github.event.inputs.versionName }} into main"
        labels: |
          automerge
           
    - name: Create a tag
      run: | 
        echo "Current tags"
        git tag 
        echo "Creating new tag ${{ github.event.inputs.versionName }}"
        git tag "v${{ github.event.inputs.versionName }}"
        git tag
        git push origin "v${{ github.event.inputs.versionName }}"
